name: BoatRestrictor
version: 1.0.0
main: ru.aspirez.boatplugin.BoatPlugin
api-version: '1.21'
commands:
  boatrestrictor:
    description: Перезагружает конфигурацию плагина
    usage: /boatrestrictor
    permission: boatrestrictor.reload
permissions:
  boatrestrictor.reload:
    description: Позволяет перезагружать конфигурацию плагина
    default: op